const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //topic
    ADD_TOPIC_SUCCESS: 'ADD_TOPIC_SUCCESS',

    CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
    CREATE_TOPIC_FAILD: 'CREATE_TOPIC_FAILD',

    EDIT_TOPIC_SUCCESS: 'EDIT_TOPIC_SUCCESS',
    EDIT_TOPIC_FAILD: 'EDIT_TOPIC_FAILD',

    DELETE_TOPIC_SUCCESS: 'DELETE_TOPIC_SUCCESS',
    DELETE_TOPIC_FAILD: 'DELETE_TOPIC_FAILD',

    FETCH_ALL_TOPICS_SUCCESS: 'FETCH_ALL_TOPICS_SUCCESS',
    FETCH_ALL_TOPICS_FAILD: 'FETCH_ALL_TOPICS_FAILD',

    FETCH_TOP_TOPICS_SUCCESS: 'FETCH_TOP_TOPICS_SUCCESS',
    FETCH_TOP_TOPICS_FAILD: 'FETCH_TOP_TOPICS_FAILD',


    //lesson list
    ADD_LESSON_LIST_SUCCESS: 'ADD_LESSON_LIST_SUCCESS',

    CREATE_LESSON_LIST_SUCCESS: 'CREATE_LESSON_LIST_SUCCESS',
    CREATE_LESSON_LIST_FAILD: 'CREATE_LESSON_LIST_FAILD',
    
    EDIT_LESSON_LIST_SUCCESS: 'EDIT_LESSON_LIST_SUCCESS',
    EDIT_LESSON_LIST_FAILD: 'EDIT_LESSON_LIST_FAILD',
    
    DELETE_LESSON_LIST_SUCCESS: 'DELETE_LESSON_LIST_SUCCESS',
    DELETE_LESSON_LIST_FAILD: 'DELETE_LESSON_LIST_FAILD',
    
    FETCH_ALL_LESSON_LISTS_SUCCESS: 'FETCH_ALL_LESSON_LISTS_SUCCESS',
    FETCH_ALL_LESSON_LISTS_FAILD: 'FETCH_ALL_LESSON_LISTS_FAILD',
    
    FETCH_TOP_LESSON_LISTS_SUCCESS: 'FETCH_TOP_LESSON_LISTS_SUCCESS',
    FETCH_TOP_LESSON_LISTS_FAILD: 'FETCH_TOP_LESSON_LISTS_FAILD',


    // admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILD: 'FETCH_GENDER_FAILD',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILD: 'FETCH_ROLE_FAILD',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILD: 'CREATE_USER_FAILD',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILD: 'EDIT_USER_FAILD',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILD: 'DELETE_USER_FAILD',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILD: 'FETCH_ALL_USERS_FAILD',


})

export default actionTypes;